### ISSUE TITLE
"Index was outside the bounds of array" Can open HCM but question marks are everywhere and all my settings/hotkeys are missing

### ISSUE THREAD

**Issue by UkuleleAversion** [topeterk/HitCounterManager#37]
**Describe the bug**
I click on Hit Counter Manager and it takes a while before I get any sign that it's opening such as asking me to run as admin. Then the following error occurs: 

> "System.IndexOutOfRangeException: Index was outside the bounds of the array.
>    at HitCounterManager.ProfilesControl.InitializeProfilesControl(Profiles profiles, Succession Succession)
>    at HitCounterManager.Form1.LoadSettings()
>    at HitCounterManager.Form1.Form1_Load(Object sender, EventArgs e)
>    at System.Windows.Forms.Form.OnLoad(EventArgs e)
>    at System.Windows.Forms.Form.OnCreateControl()
>    at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
>    at System.Windows.Forms.Control.CreateControl()
>    at System.Windows.Forms.Control.WmShowWindow(Message& m)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.Form.WmShowWindow(Message& m)
>    at HitCounterManager.Form1.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)"

**To Reproduce**
1. Create six new profiles, for a six tab multi-DLC no hit run. 
2. Wake up next day.
3. Click on HCM. 5 second wait time before anything happens. HCM usually takes a second or two to open.
4. Abovementioned error occurs.

**Expected behavior**
I expect the Hit Counter Manager to open without this error. 

**Screenshots**
![image](https://github.com/user-attachments/assets/5f9c65a7-bb32-498d-bf82-dd8b61b4cb22)
![image](https://github.com/user-attachments/assets/5751dfe3-9394-4798-9fab-af678a016a72)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: Of HCM? My version is the latest: 1.21.0.0
 
**Steps I've taken to resolve the issue:** 
- Checked HCM is on the latest version
- I ran Windows' .NET Framework Repair Tool, then restarted my computer again
- I installed the latest cumulative update for Windows 10
- Scanned my computer using Windows Defender
- Made sure .NET Framework itself is enabled through "Turn Off/On Windows Features"
- Ran System File Checker in Command Prompt but "Windows Resource Protection did not find any integrity violations"

**Additional context**
The only thing I've done differently with HCM before this problem is I started creating a multi-tab session for a multi-DLC no hit run the day before this error occurred. I've never used that feature before so maybe that's the cause?

**Comment by UkuleleAversion** [comment]
For now, it seems that HCM is working however I did have to re-do all of my hotkeys and stylesheet stuff. The splits, thankfully, were saved.

What fixed it for me was changing profile then closing the window and clicking "Yes" on Save Session Progress. Then when I opened it again the "???" and error message stopped showing.
